name: pr-checks
on:
  pull_request:
    branches: [develop, master]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    uses: ihabfallahy2/workflows-core/.github/workflows/pr-checks.yml@v1
    secrets: inherit
